receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: signoz_metrics
    ttl_days: 7

  clickhousetraces:
    endpoint: tcp://clickhouse:9000
    database: signoz_traces
    ttl_days: 7

  clickhouselogsexporter:
    endpoint: tcp://clickhouse:9000
    database: signoz_logs
    ttl_days: 7

  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [clickhousetraces, logging]

    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [clickhouse, logging]

    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [clickhouselogsexporter, logging]
